# Generated by pybaseball integration
# Date: 2026-02-13

PYBASEBALL_VERIFIED_PLAYERS = [
    ("bryce harper", "11579"),
    ("mookie betts", "13611"),
    ("elly de la cruz", "26668"),
    ("jackson chourio", "28806"),
    ("gunnar henderson", "26289"),
    ("bobby witt", "25764"),
    ("cj abrams", "25768"),
    ("jackson merrill", "29490"),
]
