"""
Pybaseball integration for player discovery and data fetching

This bridges pybaseball with our existing database structure
"""
import sys
from pathlib import Path

project_root = Path(__file__).parent.parent.parent
sys.path.insert(0, str(project_root))

from pybaseball import playerid_lookup, cache, batting_stats
import pandas as pd

# Enable caching
cache.enable()


class PybaseballBridge:
    """
    Bridge between pybaseball and our database
    """
    
    def __init__(self):
        pass
    
    def find_player_ids(self, last_name, first_name=None):
        """
        Find player IDs using pybaseball
        
        Args:
            last_name: Player's last name
            first_name: Player's first name (optional)
        
        Returns:
            List of matching players with IDs
        """
        try:
            if first_name:
                results = playerid_lookup(last_name, first_name)
            else:
                results = playerid_lookup(last_name)
            
            if results is None or results.empty:
                return []
            
            players = []
            for _, row in results.iterrows():
                players.append({
                    'name': f"{row['name_first']} {row['name_last']}",
                    'fg_id': str(int(row['key_fangraphs'])) if pd.notna(row['key_fangraphs']) else None,
                    'mlbam_id': str(int(row['key_mlbam'])) if pd.notna(row['key_mlbam']) else None,
                    'bbref_id': row['key_bbref'],
                    'debut': int(row['mlb_played_first']) if pd.notna(row['mlb_played_first']) else None,
                    'last_season': int(row['mlb_played_last']) if pd.notna(row['mlb_played_last']) else None
                })
            
            return players
            
        except Exception as e:
            print(f"Error looking up player: {e}")
            return []
    
    def bulk_id_lookup(self, player_names):
        """
        Look up IDs for multiple players
        
        Args:
            player_names: List of (first_name, last_name) tuples
        
        Returns:
            List of player dicts with IDs
        """
        results = []
        
        print(f"🔍 Looking up {len(player_names)} players...")
        
        for first, last in player_names:
            print(f"   {first} {last}...", end=' ')
            
            players = self.find_player_ids(last, first)
            
            if players:
                # Take first match
                player = players[0]
                if player['fg_id']:
                    results.append(player)
                    print(f"✅ FG ID: {player['fg_id']}")
                else:
                    print(f"❌ No FanGraphs ID")
            else:
                print("❌ Not found")
        
        print(f"\n✅ Found {len(results)}/{len(player_names)} players with FanGraphs IDs")
        return results
    
    def get_current_season_leaders(self, season=2025, min_pa=100, top_n=50):
        """
        Get top performers from current season
        
        Args:
            season: Season year
            min_pa: Minimum plate appearances
            top_n: Number of players to return
        
        Returns:
            List of player dicts with IDs
        """
        print(f"🔍 Fetching {season} season leaders (min {min_pa} PA)...")
        
        try:
            stats = batting_stats(season, qual=min_pa)
            
            # Sort by wRC+
            stats = stats.sort_values('wRC+', ascending=False).head(top_n)
            
            print(f"✅ Retrieved {len(stats)} players")
            
            # Extract player info
            players = []
            for _, row in stats.iterrows():
                # Try to find FG ID from the stats
                # pybaseball should include playerid
                players.append({
                    'name': row['Name'],
                    'team': row.get('Team', 'N/A'),
                    'pa': int(row['PA']),
                    'wrc_plus': int(row['wRC+']),
                    # Note: batting_stats doesn't include IDs directly
                    # We'll need to look them up separately
                })
            
            return players
            
        except Exception as e:
            print(f"Error fetching season leaders: {e}")
            return []
    
    def export_verified_players(self, players, output_file='pybaseball_verified.py'):
        """
        Export players in verified_players.py format
        
        Args:
            players: List of player dicts from bulk_id_lookup
            output_file: Output filename
        """
        with open(output_file, 'w') as f:
            f.write("# Generated by pybaseball integration\n")
            f.write("# Date: " + pd.Timestamp.now().strftime('%Y-%m-%d') + "\n\n")
            f.write("PYBASEBALL_VERIFIED_PLAYERS = [\n")
            
            for player in players:
                if player.get('fg_id'):
                    f.write(f'    ("{player["name"]}", "{player["fg_id"]}"),\n')
            
            f.write("]\n")
        
        print(f"\n📝 Exported {len(players)} players to {output_file}")
        print(f"   Copy these to src/data/verified_players.py")


if __name__ == "__main__":
    print("=" * 70)
    print("PYBASEBALL INTEGRATION BRIDGE")
    print("=" * 70)
    
    bridge = PybaseballBridge()
    
    # Demo 1: Look up specific players
    print("\n📋 Demo 1: Looking up specific players\n")
    
    test_players = [
        ('Bryce', 'Harper'),
        ('Mookie', 'Betts'),
        ('Fernando', 'Tatis'),
        ('Julio', 'Rodriguez'),
        ('Elly', 'De La Cruz'),
        ('Jackson', 'Chourio'),
        ('Gunnar', 'Henderson'),
        ('Bobby', 'Witt'),
        ('CJ', 'Abrams'),
        ('Jackson', 'Merrill'),
    ]
    
    results = bridge.bulk_id_lookup(test_players)
    
    if results:
        bridge.export_verified_players(results)